#!/bin/sh

logger(){>&2 echo $@;}

LFUSER="lf"
DBHOST="${POSTGRES_HOST}"
DBNAME="${POSTGRES_DB}"
DBUSER="${POSTGRES_USER}"
DBPASS="${POSTGRES_PASSWORD}"

while true; do
  nice /opt/lf/bin/lf_update host=${DBHOST} dbname=${DBNAME} user=${DBUSER} password=${DBPASS} 2>&1 | logger -t "lf_updated"
  nice /opt/lf/bin/lf_update_issue_order host=${DBHOST} dbname=${DBNAME} user=${DBUSER} password=${DBPASS} 2>&1 | logger -t "lf_updated"
  nice /opt/lf/bin/lf_update_suggestion_order host=${DBHOST} dbname=${DBNAME} user=${DBUSER} password=${DBPASS} 2>&1 | logger -t "lf_updated"
  sleep 5
done
